abstract: XML::RSS With A Liberal Parser
author: Daisuke Maki <daisuke@endeworks.jp>, Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: XML-RSS-Liberal
no_index: 
  directory: 
    - inc
    - t
requires: 
  XML::LibXML: 0
  XML::Liberal: 0
version: 0.02
