--- 
abstract: XML::RSS With A Liberal Parser
author: Daisuke Maki <daisuke@endeworks.jp>, Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: XML-RSS-Liberal
no_index: 
  directory: 
    - inc
    - t
requires: 
  XML::Liberal: 0
  XML::RSS::LibXML: 0.30
version: 0.03
